---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: Docling Serve ServingRuntime for KServe
    opendatahub.io/template-name: docling-serve-runtime
    openshift.io/display-name: docling-serve
  name: docling-serve-v0.7.0
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  containers:
    - image: 'quay.io/docling-project/docling-serve-cu124:v0.7.0'
      name: kserve-container
      command:
        - python
        - '-m'
        - docling_serve
        - run
      ports:
        - containerPort: 5001
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: Docling
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Docling Serve
    serving.kserve.io/deploymentMode: RawDeployment
  name: docling-v0-7-0
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      env:
        - name: UVICORN_WORKERS
          value: '3'
        - name: WITH_UI
          value: 'True'
      modelFormat:
        name: Docling
      name: ''
      resources:
        limits:
          cpu: '6'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '4'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: docling-serve-v0.7.0
      storage:
        key: aws-connection-models
        path: dummy/
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: "T4-gpu"
