apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: llama-guard-3-1b
    serving.kserve.io/deploymentMode: RawDeployment
  name: llama-guard-3-1b
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
          - '--served-model-name=meta-llama/Llama-Guard-3-1B'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '12'
          memory: 64Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 1Gi
          nvidia.com/gpu: '1'
      runtime: llama-guard-3-1b
      storageUri: 'oci://quay.io/rh-aiservices-bu/llama-guard-3-1b-modelcar:2.0.0'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: "l4-gpu"
        operator: Equal
