kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-models
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
    argocd.argoproj.io/managed-by: openshift-gitops    
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: models
    argocd.argoproj.io/sync-wave: "0"    
data:
  AWS_ACCESS_KEY_ID: bWluaW8tYWRtaW4=
  AWS_DEFAULT_REGION: dXM=
  AWS_S3_BUCKET: bW9kZWxz
  AWS_S3_ENDPOINT: aHR0cDovL21pbmlvLmljLXNoYXJlZC1taW5pby5zdmM6OTAwMA==
  AWS_SECRET_ACCESS_KEY: ampLWmZtUFdrNFBSelQrU1hxa2tFdz09
type: Opaque
