---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    argocd.argoproj.io/managed-by: openshift-gitops
    argocd.argoproj.io/sync-wave: "1"
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: "HuggingFace TGI - Granite Docling"
    opendatahub.io/template-display-name: "HuggingFace TGI - Granite Docling"
    opendatahub.io/template-name: tgi-granite-docling
  name: tgi-granite-docling
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '3000'
  containers:
    - args:
        - --model-id=/mnt/models
        - --port=3000
      env:
        - name: HF_HUB_CACHE
          value: /tmp
        - name: TRANSFORMERS_CACHE
          value: /tmp
        - name: NUMBA_CACHE_DIR
          value: /tmp
        - name: NUMBA_DISABLE_JIT
          value: "1"
      image: 'ghcr.io/huggingface/text-generation-inference:1.4'
      name: kserve-container
      ports:
        - containerPort: 3000
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Granite-Docling-258M
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/revisionHistoryLimit: "1"
  name: granite-docling-258m
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: pytorch
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 8Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: tgi-granite-docling
      storage:
        key: aws-connection-models
        path: ibm-granite/granite-docling-258M/
    nodeSelector:
      beta.kubernetes.io/instance-type: g6.2xlarge
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: "L4-gpu"
        operator: Equal
