---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    argocd.argoproj.io/managed-by: openshift-gitops
    argocd.argoproj.io/sync-wave: "1"
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: "vLLM-RHOAI 2.23-max-len: 8192-llama3.2-1b-fp8"
    opendatahub.io/template-display-name: "vLLM-RHOAI 2.23-max-len: 8192-llama3.2-1b-fp8"
    opendatahub.io/template-name: vllm-2.23-8192-llama3.2-1b-fp8
  name: vllm-2.23-8192-llama3.2-1b-fp8
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name={{.Name}}
        - --max-model-len=8192
        - --enable-auto-tool-choice
        - --tool-call-parser=llama3_json
        - --chat-template=/app/data/template/tool_chat_template_llama3.2_json.jinja
        - --gpu-memory-utilization=0.90
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: 'quay.io/modh/vllm:rhoai-2.23-cuda'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 4Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Llama-3.2-1B-Instruct-FP8
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/revisionHistoryLimit: "1"
  name: llama-3-2-1b-fp8
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '6'
          memory: 16Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '4'
          memory: 12Gi
          nvidia.com/gpu: '1'
      runtime: vllm-2.23-8192-llama3.2-1b-fp8
      storage:
        key: aws-connection-models
        path: RedHatAI/Llama-3.2-1B-Instruct-FP8/
    nodeSelector:
      beta.kubernetes.io/instance-type: g6e.2xlarge
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: "L40S-gpu"
        operator: Equal
---
