---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    argocd.argoproj.io/managed-by: openshift-gitops
    argocd.argoproj.io/sync-wave: "1"
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["habana.ai/gaudi"]'
    openshift.io/display-name: "TGI-Gaudi Runtime for Llama 4 Scout"
    opendatahub.io/template-display-name: "TGI-Gaudi Runtime"
    opendatahub.io/template-name: tgi-gaudi-runtime
  name: llama-4-scout-tgi-gaudi
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - --model-id=$(MODEL_ID)
        - --port=8080
        - --max-input-length=400000
        - --max-total-tokens=524288
        - --max-batch-prefill-tokens=65536
        - --max-concurrent-requests=128
      command:
        - text-generation-launcher
      env:
        - name: MODEL_ID
          value: meta-llama/Llama-4-Scout-17B-16E-Instruct
        - name: NUM_SHARD
          value: "4"
        - name: ENABLE_VISION
          value: "true"
        - name: MAX_INPUT_IMAGES
          value: "5"
        - name: ENABLE_TOOLS
          value: "true"
        - name: HABANA_VISIBLE_DEVICES
          value: all
        - name: ENABLE_HPU_GRAPH
          value: "true"
        - name: PT_HPU_LAZY_MODE
          value: "1"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: token
      image: 'ghcr.io/huggingface/tgi-gaudi:latest'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
        - mountPath: /data
          name: model-cache
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: HuggingFace
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 32Gi
      name: shm
    - emptyDir:
        sizeLimit: 250Gi
      name: model-cache
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Llama-4-Scout-17B-Gaudi
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/revisionHistoryLimit: "1"
  name: llama-4-scout-gaudi
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: HuggingFace
      name: ''
      resources:
        limits:
          cpu: '32'
          memory: 128Gi
          habana.ai/gaudi: '4'
        requests:
          cpu: '16'
          memory: 64Gi
          habana.ai/gaudi: '4'
      runtime: llama-4-scout-tgi-gaudi
    tolerations:
      - effect: NoSchedule
        key: habana.ai/gaudi
        operator: Exists
    nodeSelector:
      accelerator: gaudi
---
