---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM ServingRuntime for Mistral
    opendatahub.io/template-name: vllm-runtime
    openshift.io/display-name: mistral-7b-vllm
  name: mistral-7b-vllm
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{.Name}}'
        - '--max-model-len=4096'
        - '--enforce-eager'
        - '--chat-template=/mnt/models/tokenizer_config.json'
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: VLLM_USE_MODELSCOPE
          value: "False"
        - name: TRANSFORMERS_OFFLINE
          value: "1"
      image: 'quay.io/modh/vllm:rhoai-2.23-cuda'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Mistral-7B-Instruct-v0.3
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/revisionHistoryLimit: "1"
  name: mistral-7b-instruct
  namespace: llm-hosting  
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '8'
          memory: 24Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: 200m
          memory: 16Gi
          nvidia.com/gpu: '1'
      runtime: mistral-7b-vllm
      storage:
        key: aws-connection-models
        path: mistralai/Mistral-7B-Instruct-v0.3/
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: "L4-gpu"
        operator: Equal
