---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    argocd.argoproj.io/managed-by: openshift-gitops
    argocd.argoproj.io/sync-wave: "1"
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe
    opendatahub.io/template-name: vllm-runtime
    openshift.io/display-name: qwen38-27b-vllm
  name: qwen38-27b-vllm
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - 'serve'
        - '/mnt/models'
        - '--port=8080'
        - '--served-model-name={{.Name}}'
        - '--tensor-parallel-size=2'
        - '--max-model-len=131072'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser'
        - 'hermes'
      command:
        - vllm
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: VLLM_USE_MODELSCOPE
          value: "False"
        - name: TRANSFORMERS_OFFLINE
          value: "1"
        - name: TRITON_CACHE_DIR
          value: /tmp/triton_cache
        - name: HOME
          value: /tmp
      image: 'vllm/vllm-openai:latest'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 16Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Qwen3.8-27B-BF16
    serving.kserve.io/deploymentMode: RawDeployment
  name: qwen38-27b
  namespace: llm-hosting
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '44'
          memory: 160Gi
          nvidia.com/gpu: '2'
        requests:
          cpu: '16'
          memory: 64Gi
          nvidia.com/gpu: '2'
      runtime: qwen38-27b-vllm
      storage:
        key: aws-connection-models
        path: Qwen/Qwen3.8-27B/
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: "L40S-gpu"
        operator: Equal
