kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: custom-odh-tec
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/rh-aiservices-bu/odh-tec:latest'
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source